name: Deploy to Xserver FTP

on:
  push:
    branches:
      - main

jobs:
  ftp-deploy:
    name: Deploy to Xserver
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      
      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          # Xserver usually requires navigating into the domain's public_html folder
          server-dir: magome-yanagiya.com/public_html/
